### PR TITLE
build process using Make; add [optional] step to build a PDF

### PR DESCRIPTION
**Pull request by btbytes**

### CODE REVIEW

**Comment by haifengl** [comment]
Thanks!

**Comment by haifengl** [comment]
actually pdf is better to generate by latex tools. The output is much better than pandoc.

**Comment by btbytes** [comment]
AFAIK, pandoc uses pdflatex to convert tex to pdf. you can override that
with --latex-engine=xelatex for example.

**Comment by haifengl** [comment]
Thanks! Do you know how to include references in the generated .MD and .EPUB files?

**Comment by btbytes** [comment]
You are right about the PDF being generated from tex directly. Your workflow was unusual for me because  usually I do `md -> tex -> pdf`. I'll try to figure out how to include refs in epub.. not confident about md though..

**Comment by haifengl** [comment]
I am a long time latex user. I like it very much and use it as the base, especially when there are a lot of formulas, although it is not the case here.

**Pull request merged**
